### ISSUE TITLE
I get the 500 error

### ISSUE THREAD

**Issue by marklane2001** [cheezy/puppies#8]
Hi - When I go to rails s and go to localhost:3000 I get this

Started GET "/" for 127.0.0.1 at 2017-07-21 20:30:50 +0100
Processing by AgencyController#index as HTML
  Rendered agency/index.html.erb within layouts/application (1.0ms)
Completed 500 Internal Server Error in 3ms
^C[2017-07-21 20:33:19] INFO  going to shutdown ...

and then get the 500 error. I'm assuming this view is failing and it is then hitting the public 500 error. Unsure why though

**Comment by cheezy** [comment]
Can you tell me how you setup and started the application?

**Comment by marklane2001** [comment]
Hi ,

I cloned the site from Git. I am running rails ruby 2.4.0p0 (2016-12-24 revision 57164) [x86_64-darwin16]

I then saved the puppies file next to my Cucumber directory. I navigated to that folder and ran Bundle Install.

Everything went through. I then ran both rake commands to populate the db. The Rails s and then 500.


Thanks

**Comment by marklane2001** [comment]
Oh and i'm using a mac if this makes any difference. Thanks again for all your help.

**Comment by marklane2001** [comment]
I have resolved this issue. It turns out I was using the wrong Ruby Version for my project.
